AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template IAM_Users_Groups_and_Policies:This template creates
  IAM users, groups and policies for KIT Financial Group AWS account. 
  First group gives to CloudSpace Engineers full admin access except billing to the NAS accounts.
  Second group gives KIT Financial Group Security Team full admin access with billing included to the KIT Financial Group account.
  Third group gives KIT Financial Group Operations Team  full admin access to deploy ONLY in the us-east-1 region
  and should NOT be able to launch in any other region.
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters

Resources:

  CloudSpaceUsers:
    Type: 'AWS::IAM::User'
    Properties:
      LoginProfile:
        Password: !Ref Password
      Groups: 
        - !Ref CloudSpaceUserGroup
      Tags: 
        - Key: "Name"
          Value: "CS-User-1"
      UserName: "CS-User-1"

  CloudSpaceUserGroup:
    Type: 'AWS::IAM::Group'
    Properties: 
      GroupName: CloudSpaceUserGroup
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
        - 'arn:aws:iam::aws:policy/IAMUserChangePassword'       
  
  # CFNAdminGroup:
  #   Type: 'AWS::IAM::Group'
  # Users:
  #   Type: 'AWS::IAM::UserToGroupAddition'
  #   Properties:
  #     GroupName: !Ref CloudSpaceUserGroup
  #     Users:
  #       - !Ref CloudSpaceUser1

  BillingDeniedPolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: BillingDeniedPolicies
      PolicyDocument:
        Statement:
          - Sid: Stmt1654371600255
            Action: "aws-portal:*"
            Effect: Deny
            Resource: "*"
        # Statement:
        #   - Effect: Allow
        #     Action:
        #       - 'cloudformation:Describe*'
        #       - 'cloudformation:List*'
        #       - 'cloudformation:Get*'
        #     Resource: '*'
      Groups:
        - !Ref CloudSpaceUserGroup
#   AdminPolicies:
#     Type: 'AWS::IAM::Policy'
#     Properties:
#       PolicyName: Admins

#       PolicyDocument:
#         Statement:
#           - Effect: Allow
#             Action: 'cloudformation:*'
#             Resource: '*'
#       Groups:
#         - !Ref CFNAdminGroup
#   CFNKeys:
#     Type: 'AWS::IAM::AccessKey'
#     Properties:
#       UserName: !Ref CFNUser
# Outputs:
#   AccessKey:
#     Value: !Ref CFNKeys
#     Description: AWSAccessKeyId of new user
#   SecretKey:
#     Value: !GetAtt 
#       - CFNKeys
#       - SecretAccessKey
#     Description: AWSSecretKey of new user

# Type: AWS::IAM::User
# Properties: 
#   Groups: 
#     - String
#   LoginProfile: 
#     LoginProfile
#   ManagedPolicyArns: 
#     - String
#   Path: String
#   PermissionsBoundary: String
#   Policies: 
#     - Policy
#   Tags: 
#     - Tag
#   UserName: String
Footer
© 2022 GitHub, Inc.
